FROM apache/spark:4.1.3-scala2.13-java17-python3-ubuntu

USER root
COPY requirements.spark.txt /tmp/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt
ENV SPARK_MASTER=spark://spark-master:7077
